### ISSUE TITLE
Automatically assign bounties

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#100]
The bot should be able to automatically assign bounties if bounty hunter has no more questions.

How it should work:
1. Bounty hunter clears an issue requirements
2. Bounty hunter posts a comment "/assign" and the bot assigns bounty hunter to an issue

What should be done:
1. Add the following parameters to the github action config:
    - `auto_assign_max_unresolved_issues`: The number of max unresolved issues. There is a typical situation when bounty hunter posts a PR for the issue and wants to take the next bounty while PR is in review. We should allow him to take a new one if he has no more than `auto_assign_max_unresolved_issues` number of issues in review. By default equals to 1.

Example:
```
- name: Ubiquity Bounty Bot
  uses: ubiquity/bounty-bot@v0.0.1
  with: 
    auto_assign_max_unresolved_issues: 1
```

2. Implement the bot with the following features:
- On new comment check whether it is the "/assign" command
- On "/assign" command the bot should check that issue has not already been assigned
- On "/assign" command the bot should check that a bounty hunter has no more than `auto_assign_max_unresolved_issues` number of unresolved issues. If max number is not reached then the bot should assign user to the issue. If max number is reached then bot should post an error message:
```
@author Sorry, max number of unresolved issues reached
```

3. Update `README.md` with bot config docs.

**Comment by rndquu** [comment]
> Good forward thinking with `auto_assign_max_unresolved_issues` but I think we might need another bounty to support this with infrastructure database side.

This data should be available via github API so I would not create a new bounty for now

**Comment by 0xcodercrane** [comment]
Spec seems clear but I'd like to add a safety check to prevent scammers to use `/assign` command. 
To do this, we might need admin's confirmation or something else.

**Comment by pavlovcik** [comment]
You can only assign to yourself so there is no attack/scam vector

**Comment by pavlovcik** [comment]
Lets make a defense for it if we see it be abused. We can disable the feature entirely in a config setting as a simple defense. I think its unlikely to happen.

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x6a700452c57cafad097a32fb1b4cd99ecff2889048af7f9a7d525b5d2b337bd2
