### ISSUE TITLE
Delete Price Labels When Not Used

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#104]
I think that when an issue is closed, the bot should check if the price label in the issue is being used anywhere else. If not, then it should be removed. 

Reference code can be found here: [clearUnusedLabels](https://github.com/pavlovcik/colorize-labels/blob/069d5eab9b4207a1ee8f6d19e9ef12d6407f30cc/src/utils/clear-unused-labels/clear-unused-labels.ts#L11)

---

### Original Post

We have a ton of price labels. I'm thinking through this still, but ideally the bot should be able to delete the price label if it is no longer in use by any open issues. 

Ideally if we could hide it from the labels list when creating the issue.

The reason why I am a little hesitant though is because after the issues are closed it could be nice to retain the label data. For whatever its worth we could always see the Etherscan transaction to review things.

**Comment by pavlovcik** [comment]
@0xcodercrane do you know why github-actions is performing the actions instead of UbiquiBot[dev]?

**Comment by 0xcodercrane** [comment]
> @0xcodercrane do you know why github-actions is performing the actions instead of UbiquiBot[dev]?

yeah because embedded github token is used instead of ubiquibot app token in marketplace.yml

**Comment by 0xcodercrane** [comment]
Let me update it

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x2cc091b71653ddefd4df5b35c35fab0b13156538423380a234f5a39f0d7f2401
