### ISSUE TITLE
Enhance Weekly Summary

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#119]
https://t.me/ubtestingchannel/55 UB Testing Channel, [Feb 12, 2023 at 19:57]
new issues: 7
issues resolved: 6
total user interactions count: 68
bounties given: 1000 USD
new pulls: 11
closed pulls: 4
merged pulls: 6
total commits: 279

---

New schema, no monospace font:

📝 commits: 279 
📂 issues opened: 7
📁 issues closed: 6
📄 pull requests: 11
📑 pull requests merged: 6

---

Also we should use Proxima Nova font on the rendered image.

**Comment by pavlovcik** [comment]
This would have been a good issue for "dynamic `Time: ` labels" to calculate bounty price. I would have set this for two hours

**Comment by pavlovcik** [comment]
@Steveantor please share your wallet address. Great work here it looks awesome!

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by pavlovcik** [comment]
> Here's my address:
0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE
@pavlovcik

https://etherscan.io/tx/0xeefd1a3d36c5cfb768e8a1311284a38f2d6b8651e3ab12aee91d4544a510c99e
https://etherscan.io/tx/0xe8d1fabc7a00037cdcdc04efaadf9e69f3acdcb0aa40dc3670a7ab6da4d9eb5c
