### ISSUE TITLE
payload schema validation fails for repository with no description

### ISSUE THREAD

**Issue by zgorizzo69** [ubiquity/bounty-bot#121]
add bounty-bot on a description less repository you will get that error 
![image](https://user-images.githubusercontent.com/16853695/218851277-fc563891-fb87-43f4-843a-af4faf434a70.png)

**Comment by pavlovcik** [comment]
We're gonna need enable the PERMIT for DAI payments for these small bounties @rndquu maybe we should discuss this more and make a spec because I'm not very familiar with how to use it.
