### ISSUE TITLE
Make unassign feature working for all the issues

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#124]
https://github.com/ubiquity/bounty-bot/blob/development/src/handlers/wildcard/unassign.ts#L21

it is currently working only on `Test issue` for testing purpose. When we go to prod, we should remove it.

**Comment by pavlovcik** [comment]
@0xcodercrane you should always use permalinks because branches auto delete when merged.

**Comment by 0xcodercrane** [comment]
you're right

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xaa5c407434acb1ffc1c8c1e253df08ff76bec6742d0c6b9e1a0c90bd827d72fb
