### ISSUE TITLE
Rate Limit Header

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#134]
It would be better to read the rate limit header that's passed with the GitHub response and change behavior based on that number I think. 

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/pull/129#discussion_r1115189897_

**Comment by devpanther** [comment]
You're right, using the rate-limit header provided by GitHub API is more accurate to avoid overloading their servers.

Gonna fix this real quick

**Comment by devpanther** [comment]
@pavlovcik can you review this GitHub rate limit header fix, so I can take on the documentation?

**Comment by pavlovcik** [comment]
I'm happy to grant the exception of you working on the documentation while waiting for a review on the rate limit header fix. If the bot doesn't allow you to self assign, then I can manually assign. Just reference this comment and I'll be able to accommodate.

**Comment by devpanther** [comment]
> I'm happy to grant the exception of you working on the documentation while waiting for a review on the rate limit header fix. If the bot doesn't allow you to self assign, then I can manually assign. Just reference this comment and I'll be able to accommodate.

Thanks, it assigned me.. thought it would throw an error initially

**Comment by pavlovcik** [comment]
We still need to create the feature to enforce this DevPool rule inside of the bot logic.
