### ISSUE TITLE
Conventional Commits Commit Hook

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#140]
I see that conventional commits didn't pass. I am willing to let it slide but we should take the commit hook from the `ubiquity-dollar` repo to minimize this from happening again. I'll set it as a new issue.

**Comment by 0xcodercrane** [comment]
I think its already done on bounty repo with latest commits. can I close the issue?

**Comment by pavlovcik** [comment]
I think it's referring to how we need to support the built in GitHub messages as well. Like "merged from development" should pass.

**Comment by pavlovcik** [comment]
I'll review today and verify. Not sure what happened here from my phone.
