### ISSUE TITLE
Avoid GitHub Action Invocation Upon Bot Invoked Event

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#15]
Under the [Actions](https://github.com/ubiquity/bounty-bot/actions) tab, it would be far cleaner if GitHub didn't run another based on the bot doing something (e.g. changing the labels, and then invoking the Bot to run again as a response to itself.)

I was able to make it skip the main logic if it detects that the Action was invoked by the bot, but it still pollutes the Actions runs history.

**Comment by pavlovcik** [comment]
@0xcodercrane I think you completed this I can send you the payout if you post your address here!

**Comment by 0xcodercrane** [comment]
> @0xcodercrane I think you completed this I can send you the payout if you post your address here!

0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xc0ed067c81672641a0eb10f09ef2c70f2b2dd4df7606ad949a341dcf06f85979
https://etherscan.io/tx/0x3ddf2ed1ca4a91531a626f805f5055bb04388e6ecc28032e1382631efca74068
