### ISSUE TITLE
Fix Comment Formatting

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#156]
I think it looks neater when addresses are all in monospace formatting. Make sure that addresses are always monospaced.

Some recent examples where its normal text formatting:
1. https://github.com/ubiquity/bounty-bot/issues/146#issuecomment-1451355192
2. https://github.com/ubiquity/bounty-bot/issues/148#issuecomment-1452008402

An exception for the claim button comment formatting: the address should be monospace AND truncated 

1. https://github.com/ubiquity/ubiquity-dollar/issues/592#issuecomment-1452238250

**Comment by pavlovcik** [comment]
Oh @Steveantor you forgot to use the /assign command

**Comment by pavlovcik** [comment]
Hey @0xcodercrane how can I have the bot generate a payment permit? I thought the conditions were correct here (unless @Steveantor has not yet registered their wallet address?)

**Comment by Steveantor** [comment]
> Oh @Steveantor you forgot to use the /assign command for automatic payouts.

Yeah wasn't around for a quite while @pavlovcik

**Comment by pavlovcik** [comment]
lol

**Comment by pavlovcik** [comment]
@0xcodercrane please look into this

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xc5b0909d0194fc511042dd63a60791444d3a7a9b327bca7cc32536dd6ccd0182
