### ISSUE TITLE
`/help` command

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#157]
The bot should have a `/help` command that simply lists all of the commands and a brief description of what they do.

**Comment by 0xcodercrane** [comment]
> The bot should have a `/help` command that simply lists all of the commands and a brief description of what they do.

Would you be handling to write docs/instruction here?

**Comment by pavlovcik** [comment]
Just list all of the / commands. Like what you have probably seen in most command line tools.

**Comment by 0xcodercrane** [comment]
ok

**Comment by pavlovcik** [comment]
Does it ignore closed issues?

**Comment by pavlovcik** [comment]
Also I don't see a payout link. Does that mean it failed/we ran out of cash in the wallet?
