### ISSUE TITLE
Fix Schizo Bot

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#159]
Bot shouldn't ask itself questions. Or any questions to the "mannequin" DevPool account.

              @ubiquity-bounties would you please post your wallet address here?

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/bounty-bot/issues/98#issuecomment-1453148603_

**Comment by Steveantor** [comment]
I forgot this one

**Comment by Steveantor** [comment]
Trying to generate the permit link since the bot missed it due to supabase outage.

**Comment by pavlovcik** [comment]
@Steveantor looks like you haven't claimed!

**Comment by Steveantor** [comment]
> @Steveantor looks like you haven't claimed! Is it working for you?

I'm waiting for the gas fees to calm down lol, we might have a batched claim option @pavlovcik

**Comment by pavlovcik** [comment]
I thought thorough rolling up permits but unfortunately the most pragmatic solution is simply to use Optimism.
