### ISSUE TITLE
Duplicate Price Labels

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#16]
Bot should be sure to clean all Price labels before setting a new one to ensure a single Price label per bounty.

Reference: https://github.com/ubiquity/bounty-bot/issues/14#issuecomment-1313395289

**Comment by pavlovcik** [comment]
Seems like this issue isn't consistent. Will need to make it more robust

**Comment by 0xcodercrane** [comment]
Its basically done [here](https://github.com/ubiquity/bounty-bot/blob/main/src/handlers/price/action.ts#L40)
