### ISSUE TITLE
Only Post Permit/Claims on "Closed as Completed" Issues

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#160]
I closed this issue as unplanned and the bot posted a claim for the assignee.              

> @0xcodercrane **[ [ CLAIM 100 ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMTAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTAwODk2MzI1NTg4NTIwODY0OTg4NDExODgzODU4NjQ0NzU1OTA2OTQyOTAzNDQ0OTQxOTE4MDM5ODkyNzAxNDc1NTU3NTk2NjQ3MTI4IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgwMDg2OEJCM0JBMkIzNjMxNmMyZmM0MkU0YUZCNkQ0MjQ2Yjc3RTQ2IiwicmVxdWVzdGVkQW1vdW50IjoiMTAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg3NGNlN2RlYmY4NTAyNjdmYmY2MzkxMzRjNzY4MWEwOWI5Njc0NTQ5NDkzOGUxZjFjZDVmNTY5MDFlOTY3YjE0M2FkNzY3Zjc4ODcxN2FlNmI0NmE2ZDEyMTNjZTkzM2NkNTQ1Mzg5NmQyNmNkMzJjMzYwNzc3OWIyOWYwOTkxZDFiIn0=) for 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/bounty-bot/issues/73#issuecomment-1453153303_

**Comment by Steveantor** [comment]
I forgot this one

**Comment by Steveantor** [comment]
Trying to generate the permit link since the bot missed it due to supabase outage.
