### ISSUE TITLE
DevPool "wallet address"

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#172]
For the dedicated DevPool account, the bot should not request to pay it.

> @ubiquity-bounties would you please post your wallet address here?

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/bounty-bot/issues/140#issuecomment-1458674268_

**Comment by 0xcodercrane** [comment]
It should be fixed with [SteveAnt's PR](https://github.com/ubiquity/bounty-bot/pull/162). Let me test it here.

**Comment by 0xcodercrane** [comment]
ok worked fine. keep the issue closed
