### ISSUE TITLE
Truncated wallet address length

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#173]
Sorry but small detail: I would like the truncated wallet address to closer match the width of the claim "button"

Ideally it grows in length based on the amount of DAI paid out. Would you mind adjusting it? To do this dynamically you can parse the amount as a string, and then check the `string.length`.

---

### [ CLAIM 1 DAI ]
`0x12345...12345`

### [ CLAIM 10 DAI ]
`0x123456...123456`

### [ CLAIM 100 DAI ]
`0x1234567...1234567`

### [ CLAIM 1000 DAI ]
`0x12345678...12345678`

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/issues/166#issuecomment-1458669417_

**Comment by 0xcodercrane** [comment]
Why didn't bot set price for the issue?

**Comment by pavlovcik** [comment]
> Why didn't bot set the price label for the issue?

I think it was broken temporarily

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x2cc55fa1432719dd520d32ad3c7ef5e24750ab6ddcb06810133585e38430e075
