### ISSUE TITLE
UbiquiBot Capabilities - v1 Specification

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#18]
### Discussed in https://github.com/ubiquity/bounty-bot/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **pavlovcik** September 10, 2022</sup>
### Bounty Setup

- [x] #19
  - Not sure what conditions should invoke this logic. Perhaps if Bounty Hunters say a keyword or phrase. Many say something along the lines of "I would like to take this bounty."
- [x] #20
  - If the Bounty Hunter took double the allotted time, then they are disqualified for the bounty and the bounty should be released back into the devpool (assigned to @ubiquity-bounties)
  - The bot should also leave a comment notifying the Bounty Hunter that they have been disqualified.
- [x] #21
  - The script currently has a small table in it that essentially multiplies a (base rate $) * (profitability score) * (time estimate score.)
  - If a Bounty Master sets any labels (profitability and/or time) then the bot is able to determine a price for the bounty.

### Payments

- [x] #22
  - This should regex for Ethereum addresses in comments of those who do not already have a registered address.
    - It could look for comments that contain "my wallet" and a regex match for an Ethereum address.
  - Safety features should not allow automatic replacement/updating of their address in the database (can be done manually.) 
  - We could check the previous comment to see if it was from a Bounty Master requesting for their wallet address (matching keywords "your wallet")
  - Upon registration, the bot should comment immediately confirming the wallet registration and its address.
- [x] #23
  - This is [spec'd out](https://github.com/ubiquity/bounty-bot/issues/13) to allow for automatic payments OR queuing payments via Gnosis Safe. 
  - This should check if the Bounty Hunter has a registered address in the database. If they don't the Bounty Bot should request for their address and then request payment from the bounty masters (could be simpler logic to implement this way; otherwise its best for the bot to handle collecting the payment address and then also automatically making the payment and posting the transaction hash)
  - Should also check who recruited the Bounty Hunter and give them their commission. 
- [x] #24
  - This can look for Etherscan transactions posted by Bounty masters.
  - The bot should confirm the logging of this transaction via a comment.

### Communication

- [x] #25
  - The comment can ask about updates related to the bounty.
- [ ] #26
  - If there are bounties that were created and haven't been solved in at least 7 days, then post a message in the Telegram chat every Monday announcing the latest unsolved bounties, along with their prices and links.

### Incentives

These incentives should all be paid out at the time the bounty is solved. During the bull market (with high gas fees) it may be wise to handle all bounty payments on an L2 like Optimism.

- [x] #27
  - Stale bounties should increase in price over time in order to ensure that every bounty will eventually be solved.
- [x] #28
  - We should give either a flat fee or a percentage of the bounty based on the quality of the specification provided by the bounty creator. This incentivizes delegation from core developers, and if those bounties are approved, definitely helps scale our development throughput.
- [x] #29
  - This should be a flat fee, or base it a logarithmic function (I throw this out there because sometimes devs do something crazy like include node_modules or format the codebase with the wrong settings) of lines changed which can compensate our Bounty Masters to review PRs.
  - We should include a bonus for speedy turnarounds (linear drop off for 24 hours from when the PR was opened to $0 compensation?)
- [x] #30
  - Meaning Bounty Masters helping Bounty Hunters via comments (e.g. bounty and/or onboarding q&a in the issue/PR)
  - We want to incentivize rapid and high quality responses from Bounty Masters to Bounty Hunters in order to unblock them.
  - We could credit $1 per word or something like that per comment/response and multiply that with the linear dropoff idea mentioned above
- [x] #31
  - Send an extra +20% of the bounty value to the recruiter of the Hunter who solved the bounty.</div>

**Comment by 0xcodercrane** [comment]
## How to implement
  
  The bounty bot should perform actions based on github events. It also performs regular actions at a regular interval like to unassign bounties if the hunter was taking but no longer interested.  
  
  ### Testing
  We need to add unit test for bot to make it stable. [Here](https://probot.github.io/docs/testing/) is a guide from probot.
  
  ### Deployment
  We can deploy bot app anywhere described in [probot docs] (https://probot.github.io/docs/deployment/). Right now, the basic bot is running on github runner based on `labeled` and `unlabeled` events. Its difficult perform regular actions / custom actions. 
  So we need to develop serverless bot and deploy it to severless service (we can use free services right now). All the deployments should be happened in github ci/cd automatically.
  
  ### Logging
  Logging is an important feature to monitor the bot. Probot has a embedded pino logger instance which can be connected to monitoring services like logdna. We need to use Probot logs instead of using `console.log`

**Comment by pavlovcik** [comment]
> Its difficult perform regular actions / custom actions under the current architecture.

I disagree. We can make it run on all events quite easily with an adjustment to the yml config. The core bot code has a generalized event response controller to easily plug in specific event response logic.

**Comment by pavlovcik** [comment]
> regular actions at a regular interval like to unassign bounties

Because of the six hour run time, what if we just have a switch case fall through where every time the bot is invoked, it handles everything it needs? 

I dislike the concept of making our core architecture around cron jobs because of wasted resources running without doing anything.

**Comment by pavlovcik** [comment]
We can consider this discussion as the v1 spec of the bot but I still feel uncomfortable with your approach of forking the discussion and making unspecified issues before the original ideas are fleshed out. Keeping issues in sync with the latest research is going to be extremely tedious with this approach.
