### ISSUE TITLE
Tutorial for new Bounty Hunters

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#183]
When a hunter posts for the first time we should display the /help menu and a greeting so that they know what they can handle themselves (in this case if they knew about the assign function that would be great)

---
Hi @pavlovcik 

Can you assign this bounty to me? 

_Originally posted by @jpldcarvalho in https://github.com/ubiquity/ubiquity-dollar/issues/578#issuecomment-1459925989_

**Comment by jpldcarvalho** [comment]
You can also add it to the DevPool Flow page (https://dao.ubq.fi/devpool-flow)

**Comment by pavlovcik** [comment]
Thanks for the suggestion. I'll do that now!

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x1c0eaf0f861d5bdad6f8c3cfc4e8a988a7ae8ae8a007ee0229e639e76e86d0f2
