### ISSUE TITLE
Generalized Contributor Financial Incentives: Pull Request Reviews

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#184]
This doubles as a system to filter out low performers from taking too much attention from the repository maintainers (pull request reviewers.)

UbiquiBot will use the "Standardized Contributor Compensation" strategy ([financially incentivize](https://github.com/ubiquity/bounty-bot/discussions/70)) reviewers on pull requests, but add a warning via a comment if the review budget exceeds the bounty budget: 
- That usually means that the bounty hunter is taking a disproportionate amount of time from the reviewers to solve the bounty, and its probably greater return-on-investment to drop/deprioritize the reviews for them.
- This will be calculated when reviews are submitted using the built-in GitHub features.

**Comment by sergfeldman** [comment]
Expected performance can be measured in 
- Timing (ie days to solve the bounty)
- Team effort (ie number of PRs to review)

**Comment by pavlovcik** [comment]
@Draeieg I remember that you had some heuristics related to this issue. Can you share them here?

**Comment by Steveantor** [comment]
How this should be implemented?

**Comment by pavlovcik** [comment]
@Draeieg here's a follow up

**Comment by Draeieg** [comment]
> How this should be implemented?

we've gathered [data](https://dao.ubq.fi/performance-minimums) on how good and terrible bounty hunters perform on average

If the bounty hunter is withing the comments, code changes and review requested for perfect performance his health bar will remain green

as the bounty hunter reaches the maximum amount of comments his health bar will turn into red and after exceeded the hunter "dies" and gets unassigned from the bounty 

with yellow and everything in between being calculated from the differences in those two data points we can develop a formula to encompass all of those parameters, for simplicity I'm going to use only reviews as an example:

if the expected performance is 1 review  and the maximun is 5, then 6=dead
5-1=4, so 50% health bar(yellow)=2 reviews as 50% of 4 is 2

after the hunter dies or completes a bounty  we have 3 ways on going about it
1) gets with full health for his next bounty with no penalty until he keeps dying and as a result gives up
2) gets with full health for his next bounty BUT there is a finite amount of lives that get replenished after each successful bounty
3) there is no health regen or proper "lives" after a successful bounty the hunter recovers some health, if the hunter dies previously  the he comes back with an amount of life dependent on the amount of times he has dies 
(by example the first time it dies comes back with 50%hp, next one 40%, next one 30% and so on until he cant revive anymore unless he finishes a bounty)

**Comment by pavlovcik** [comment]
I also remember that I wrote an idea somewhere related to an ascii art health bar I can't seem to find at the moment. Will replace this comment if I do find it. If somebody else finds it please post!

Sorry these days have been hectic for me looking for a new place to live.

**Comment by pavlovcik** [comment]
@Steveantor looks like this has a bug lol it keeps showing help every time.

**Comment by pavlovcik** [comment]
Test bot hotfix

**Comment by Steveantor** [comment]
Test bot hotfix

**Comment by pavlovcik** [comment]
@0xcodercrane I made refined this bounty for you. This is what I've been asking you about all month basically.
