### ISSUE TITLE
Assign command should clear out all other assignees.

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#185]
In the below referenced issue, there are now two assignees: @ubiquity-bounties and @0xcodercrane.

This is a problem because the "open bounties" technically are any issues assigned to @ubiquity-bounties, so this assigned issue will show up on that filtered view and new bounty hunters may be confused.

> /assign

_Originally posted by @0xcodercrane in https://github.com/ubiquity/bounty-bot/issues/104#issuecomment-1455301573_

**Comment by Steveantor** [comment]
it looks like https://github.com/ubiquity/bounty-bot/pull/197
is redundant since
https://github.com/ubiquity/bounty-bot/blob/7d4e791214650a77a34879fcb6c8d344bba27025/src/handlers/wildcard/unassign.ts#L33
does that

**Comment by pavlovcik** [comment]
Thanks for the research! Because you finished #197 we will close the pull request and reward you the bounty!

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x88402a09ee50aee24a8fc19cfd00058153a13656f3c5027c7bbc2ef2619fe0dd
