### ISSUE TITLE
Confirm Payment Permit Generation Feedback

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#192]
@0xcodercrane no payment permit was issued by the bot here. Can you throw an error or provide some type of feedback if it had a problem? Let me know what you think happened here. Thanks!

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/593#issuecomment-1475420735_

**Comment by pavlovcik** [comment]
Can you make sure that if there is an error of some sort that it lets us know in a comment?

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

There's a linked PR

**Comment by pavlovcik** [comment]
> Can you make sure that if there is an error of some sort that it lets us know in a comment?

From an architecture perspective, perhaps we can make sort of a standard callback function after a command handler is invoked to always leave a comment as a response. In this way, the bounty-bot developer would intentionally have to tell the bot to not leave a comment/response after a bot command is invoked.

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

yes

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

there's a linked PR
