### ISSUE TITLE
`autoPay` Fixes

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#193]
Oh interesting that you made a repository wide config. My vision was to have it issue specific. 

We need some adjustments: 

1. By default it should be enabled. However, once the multisig/permit idea is implemented (@rndquu is researching now) the config property should be representing the cutoff price for autopay to require approval via multisig. e.g. `autoPayThreshold: 100` to automatically pay bounties less than $100
2. We should have it configurable on the issue/bounty level because this feature is really useful to leave on EXCEPT for changes to CI. With those, its easier to test if we just merge the PR and test and then manually do the payout.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/593#issuecomment-1478932022_

**Comment by rndquu** [comment]
We could add 2 parameters to the bot's config:
1. `autoPayThresholdUsd: number`: if bounty reward is <= `autoPayThresholdUsd` then use permit2 else use gnosis safe
2. `labelsDisableAutoPay: string[]`: array of labels for which autopayments (both permit2 and gnosis safe) are disabled. So in case of the ubiquity dollar repo, if `labelsDisableAutoPay` equals to `["Devops"]` then all issues with the `Devops` label won't have automatic payments, only manual.

**Comment by pavlovcik** [comment]
> 2. 
Great idea

**Comment by pavlovcik** [comment]
I can't provide a time estimate until I understand the architecture for 1. 

@rndquu when your research is ready, can you assign a time label here?

**Comment by pavlovcik** [comment]
Hey @rndquu do you have any updates related to the research

**Comment by rndquu** [comment]
> Hey @rndquu do you have any updates related to the research?

I can't put a time estimate because gnosis safe research is not ready yet (see this [comment](https://github.com/ubiquity/bounty-bot/discussions/155#discussioncomment-5453988))

**Comment by pavlovcik** [comment]
@rndquu following up

**Comment by rndquu** [comment]
@pavlovcik 

We can close this issue as "not planned" because:
1. The `autoPayThreshold` param is already described here https://github.com/ubiquity/bounty-bot/issues/274
2. The feature of disabling payouts for particular issues is already described here https://github.com/ubiquity/bounty-bot/issues/290
