### ISSUE TITLE
Unassign to `@ubiquity-bounties`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#194]
@0xcodercrane until we officially transition to making "no assignee" the default DevPool role, the bot should technically reassign to @ubiquity-bounties!

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/578#issuecomment-1480687396_

**Comment by Steveantor** [comment]
Trying to generate the permit link since the bot missed it due to supabase outage.
