### ISSUE TITLE
`/assign` Error Message

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#203]
The bot should either 1. assign as expected or 2. reply with a message explaining what conditions must be met for the bounty to be eligible to be assigned:

> Liu:
its working only for bounties
I was assuming bounty has 2 labels
priority and time
but it was missing one

---
              /assign

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/issues/183#issuecomment-1484043169_

**Comment by pavlovcik** [comment]
This is not eligible for a bounty because this was a working basic feature that has mysteriously broken.

**Comment by Steveantor** [comment]
> @ubiquity-bounties The time limit for this bounty is on 3/27/2023

seems like the bot parses the comments incorrectly

**Comment by pavlovcik** [comment]
> > @ubiquity-bounties The time limit for this bounty is on 3/27/2023
> 
> seems like the bot parses the comments incorrectly

What do you mean?

**Comment by Steveantor** [comment]
> > > @ubiquity-bounties The time limit for this bounty is on 3/27/2023
> > 
> > 
> > seems like the bot parses the comments incorrectly
> 
> What do you mean?

I missed the assignment, thought the bot parsed your /assign command on the description.

**Comment by 0xcodercrane** [comment]
Would you be posting the testing result here? The quick step is as the following

1/ Install ubiquibot[dev] app to your forked repository.
2/ Create an issue and test out the feature the PR covers
3/ Post a proof of working
