### ISSUE TITLE
`/wallet` address not persisting

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#204]
@Steveantor would you please post your wallet address here?

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/bounty-bot/issues/110#issuecomment-1484045913_

**Comment by pavlovcik** [comment]
Another hotfix that is an essential feature.

**Comment by 0xcodercrane** [comment]
Ok I had a deep debug on this. bountybot supabase project has been paused temporarily.

**Comment by 0xcodercrane** [comment]
> @0xcodercrane would you please post your wallet address here?

I don't need to post my address because its not a bounty lol

**Comment by pavlovcik** [comment]
@0xcodercrane you should be mindful to close these as not planned if they aren't meant to be paid out (or else the permit could be generated when autoPay is enabled by default again.)
