### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Steveantor** [ubiquity/bounty-bot#205]
Test issue

**Comment by Steveantor** [comment]
Test

**Comment by pavlovcik** [comment]
> You have been unassigned from the bounty @Steveantor

This is dope to see

**Comment by 0xcodercrane** [comment]
> ### Available commands
> ```
> - /assign: Assign the origin sender to the issue automatically.
>         ex: /assign
> 
> - /wallet <WALLET_ADDRESS | ENS_NAME>: Register the hunter's wallet address.
> 	ex1: /wallet 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
> 	ex2: /wallet vitalik.eth
> ```

Thanks dev bot you are working properly

**Comment by 0xcodercrane** [comment]
wtf something changes in wallet register handler it should not be happening. @pavlovcik @Steveantor
