### ISSUE TITLE
`/unassign` command

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#207]
This should allow a bounty hunter to release a bounty back into the DevPool (assign to @ubiquity-bounties)

              We need to actually create the `/unassign` function for this feature to work!

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/pull/196#pullrequestreview-1357989238_

**Comment by 0xcodercrane** [comment]
@Steveantor  you were working on the unassigned bounty? lol

**Comment by 0xcodercrane** [comment]
The supabase project has been paused for a while because there was no traffic within at least 1 week. Would you be posting your wallet address @Steveantor ?

**Comment by 0xcodercrane** [comment]
This is the hotfix for `/unassign` command. https://github.com/ubiquity/bounty-bot/pull/215

**Comment by Steveantor** [comment]
> The supabase project has been paused for a while because there was no traffic within at least 1 week. Would you be posting your wallet address @Steveantor ?

Okay, here's my address: `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`

**Comment by Steveantor** [comment]
I wonder if supabase is even reliable if it's gets paused that way 🤔

**Comment by pavlovcik** [comment]
I noticed that this no longer has a price label. Is it because there are no other bounties with the `Price: 25 USD` label, and so when this was closed, the bot deletes the label (removing it from this bounty?)

**Comment by Steveantor** [comment]
> I noticed that this no longer has a price label. Is it because there are no other bounties with the `Price: 25 USD` label, and so when this was closed, the bot deletes the label (removing it from this bounty?)

the bot deletes the price label if it's no longer being used, those won't appear on the labels list @pavlovcik
