### ISSUE TITLE
Setting Prices for Bounties

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#21]
## Setting Prices for Bounties

It has been basically done but there could be some cleanup/enhancements/modification.

**Comment by pavlovcik** [comment]
lol how did you test this? We should set up a better workflow for fixing CI cause this always feels like a mess. 

1. It was missing the required `action.yml` file 
2. After adding it I hit an error `Payload schema validation failed!!!` see more below

https://github.com/ubiquity/bounty-bot/actions/runs/3554712235/jobs/5970975362

**Comment by 0xcodercrane** [comment]
Above issues have been fixed already by the way, I'd like to write down about improvements for setting price here

**Comment by pavlovcik** [comment]
It might make more sense to post in a discussion if its open ended?

**Comment by 0xcodercrane** [comment]
> It might make more sense to post in a discussion if its open ended?

I will start a new issue with improvement proposal.

**Comment by pavlovcik** [comment]
Just keep in mind that for larger ideas, discussions are probably the best way to compile all the ideas together, and then once its clear on the discussion, to then break it off into separate issues for each task. 

Its good to organize issues in such a way that its easy to delegate with clear specifications, and separate issues as much as possible. That way we can tag in the others for help and complete the product development faster!
