### ISSUE TITLE
Staging environment setup

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#216]
**Problems**
There's no way to test out a new feature until it gets merged to the `main` branch right now. 

**How to solve** 
- [x] Install Ubiquibot[dev] on bounty-bot repository
- [x] Create another netlify function connected to the `development` branch
- [x] Update webhook url on dev app settings. 

 This is not an ideal setup but we can make sure new features working at least before pushing it to production.

**Comment by pavlovcik** [comment]
> Update webhook url on dev app settings.

I moved UbiquiBot[dev] to Ubiquity and updated the webhook to https://ubiquibot-staging.netlify.app/.netlify/functions/webhooks

---

However I disagree with this approach for staging. Its best if we allow bounty hunters to fork the repository and we use their repositories for automatic staging environments. Its great to clearly test things per instance if we have several bounty hunters working on the bot at the same time.

**Comment by pavlovcik** [comment]
lol two permits

**Comment by sergfeldman** [comment]
### [ **[ CLAIM 400 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMzc1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI5ODk1NDU0MTcwNjE1OTA0MzUyODA5OTc5OTQ3ODQ0NjE1OTkyNjU2MjY1OTMyMjI4MDcyNjI4NzAwNjE1MjE5MzIzODYwMjE2ODQ0NiIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4ZjM5ZmQ2ZTUxYWFkODhmNmY0Y2U2YWI4ODI3Mjc5Y2ZmZmI5MjI2NiIsInJlcXVlc3RlZEFtb3VudCI6IjM3NTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHhiOWEzN2JiMDE5MDgxM2NlZGU4YThmZmZmMTBkMDFjZmIyOWM2MGEyNzUyMjlhZjQ0MDM5YTNlNzM2NWViZDY5MmI4ZDZjN2NmOWQ3NTg3YmU0YWM5ODcwNzY2ZWM4ZjJkYjZiOTZlOGU2NTljNGNkNDdhNDE5MmExYTA5MjBkZDFjIn0=)
```0xf39fd6e5...ffb92266```

**Comment by Steveantor** [comment]
What's the procedure to spin up these staging environments,
assuming I'd have 2-3 branches on my fork at a time working on different issues.

**Comment by pavlovcik** [comment]
> What's the procedure to spin up these staging environments, assuming I'd have 2-3 branches on my fork at a time working on different issues.

@0xcodercrane

**Comment by 0xcodercrane** [comment]
I apologize for my late response guys. there's no specific procedure for staging environments.

1/ Install Ubiquibot[dev] into your repository.
2/ Create a PR into `ubiquity:development` branch for your work
3/ Merge it once approved
4/ You can test out the feature by creating test-purpose issues on your forked repository, no mather whatever the branch is

**Comment by 0xcodercrane** [comment]
> I still think that we should allow developers to fork and run the bot from their own forks (via GitHub Actions as it was formerly implemented) to use each fork (and branch) as staging.

It will repro complexities to developers as we've already experienced in the first integration.

**Comment by 0xcodercrane** [comment]
Here's a list of complexity items that I'm thinking of so far.

To run via Github Actions on a forked repo, developers should set up env variables. they're 
1/ appId and privateKey of ubiquibot[dev] (They can also create an app themselves but they wouldn't do that because its kind of tedious stuff from my experience)

2/ If they have to use ubiquibot[dev] on forked repos, we should let them know env variables we set in our staging repo. I will follow up on your decision on it @pavlovcik

**Comment by 0xcodercrane** [comment]
> I apologize for my late response guys. there's no specific procedure for staging environments.
> 
> 1/ Install Ubiquibot[dev] into your repository. 2/ Create a PR into `ubiquity:development` branch for your work 3/ Merge it once approved 4/ You can test out the feature by creating test-purpose issues on your forked repository, no mather whatever the branch is

What I am thinking here is to make staging env working on the PR without merging (of course if it gets merged, the changes will def work)

**Comment by pavlovcik** [comment]
Yes let's make dev bot all public/shared env for easy development. We just need to make its permissions close to 0 as possible.

**Comment by Steveantor** [comment]
> I apologize for my late response guys. there's no specific procedure for staging environments.
> 
> 1/ Install Ubiquibot[dev] into your repository. 2/ Create a PR into `ubiquity:development` branch for your work 3/ Merge it once approved 4/ You can test out the feature by creating test-purpose issues on your forked repository, no mather whatever the branch is

could u show me an example on your repo?
@0xcodercrane

**Comment by pavlovcik** [comment]
> > I apologize for my late response guys. there's no specific procedure for staging environments.
> > 1/ Install Ubiquibot[dev] into your repository. 2/ Create a PR into `ubiquity:development` branch for your work 3/ Merge it once approved 4/ You can test out the feature by creating test-purpose issues on your forked repository, no mather whatever the branch is
> 
> could u show me an example on your repo? @0xcodercrane

I noticed that @0xcodercrane doesn't check GitHub notifications much lately so I highly recommend you follow up on Telegram as well.

**Comment by 0xcodercrane** [comment]
https://github.com/0xcodercrane/bounty-bot/issues/1

created an example by forking. please go through the above issue and let me know if you have more questions @Steveantor  @pavlovcik
