### ISSUE TITLE
The Database Gets Paused

### ISSUE THREAD

**Issue by Steveantor** [ubiquity/bounty-bot#217]
The supabase project has been paused for a while because there was no traffic within at least 1 week. Would you be posting your wallet address @Steveantor ?

_Originally posted by @0xcodercrane in https://github.com/ubiquity/bounty-bot/issues/207#issuecomment-1486132606_

If supabase gets paused due to inactivities it's a critical issue as the bot relies on it.

**Comment by 0xcodercrane** [comment]
Would you be posting a proposal how we could handle this case?

**Comment by pavlovcik** [comment]
I think this is a non issue because Supabase pauses due to inactivity. Assuming the bot is used, the instance should not be paused.
