### ISSUE TITLE
Rerequest payout command

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#225]
Right now if there was an error on permit generation then there is no way for a bounty hunter to rerequest a payout.

What should be done:
1. Use issue number for nonce on permit generation (to prevent double claims)
2. Add a `/payout` command which regenerates and posts a permit URL

Also check an edge case when bounty bot is set for 2 repositories in a single organization. This way nonces could intersect if the same private key is used for permit generation in 2 repositories. We could use smth like `int(keccak256(${issue.number}${organization.name}${repository.name}))` for the nonce.

**Comment by pavlovcik** [comment]
Let's keccak256 encode the issue ID. It should provide a uniquely accessible reference ID from the GitHub API. 

I think this is superior in case the repository or organization is renamed. But I presume the issue ID is unique and persists even after renames.
