### ISSUE TITLE
Dynamic Help Menu

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#233]
We should have a central object that stores all of the commands, as well as the help menu description of each. This way, if any new commands are created, the developer is forced to also write a description for it and it will automatically populate in the help menu.

Pseudo code because on phone:

```
const userCommands = {

assign: { 
  handler: Function;
  description: String;
},

help: { 
  handler: Function;
  description: String;
},

disableAutoPay: { 
  handler: Function;
  description: String;
},

recruit: { 
  handler: Function;
  description: String;
},

}
```

We could also separate and make two other objects, `treasurerCommands` and `adminCommands` see #221 for more context on these roles.

**Comment by devpanther** [comment]
Still open? @pavlovcik

**Comment by pavlovcik** [comment]
Use the assign command

**Comment by devpanther** [comment]
> disableAutoPay

Does these `treasurer` and `admin` commands exist right now.

I can see alot command handlers, and just two are in the help menu

`[IssueCommentCommands.ASSIGN]: assign,
  [IssueCommentCommands.UNASSIGN]: unassign,
  [IssueCommentCommands.WALLET]: registerWallet
`

but no treasurer commands @pavlovcik

**Comment by devpanther** [comment]
And what's the supabase used for?, it's not working on my local version and docs never mentioned it use

**Comment by devpanther** [comment]
![Screenshot 2023-04-07 at 6 41 56 PM](https://user-images.githubusercontent.com/42383942/230653246-9b8f3e99-5f5c-4681-ad47-0f36b4139c02.png)

Recent result

**Comment by devpanther** [comment]
0xf76F1ACB66020f893c95371f740549F312DEA3f1

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xe71b965046db71ce5f08b5aec9d2db20c350c030cdbd44457b51d192e366da41
