### ISSUE TITLE
confirming all parameters set prior to closing open issues

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/bounty-bot#237]
I closed an issue that did not have priority set but did have time set.  my understanding is that such a situation will end up with the bounty hunter not getting paid. The bot should not allow the closing of an issue unless all mandatory parameters are set. If they are not all set, the bot should indicate which are not so that the bounty master can correct.

**Comment by pavlovcik** [comment]
Updated process: https://github.com/ubiquity/bounty-bot/issues/246. The issue can not be assigned through the bot (`/assign` command) unless the prerequisites are met. 

You were using privileged functions through the GitHub UI (as a core team member) which intentionally is allowed to override standard DevPool behavior.
