### ISSUE TITLE
Pull Request Dynamic Status Update

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#243]
The bot should be able to automatically detect associated PRs with a current bounty in order to detect bounty hunter activity instead of relying on the bounty hunter to manually comment on the issue with an update.

---
              > Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

There's a linked PR

_Originally posted by @Steveantor in https://github.com/ubiquity/bounty-bot/issues/192#issuecomment-1501464389_

**Comment by pavlovcik** [comment]
Not sure on a time label. I'm guessing its either `<1 Day` or `<1 Week`

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

yes

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

There's a linked PR
