### ISSUE TITLE
Add a whitelist feature for permit2 generation

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#258]
## Problems to solve
We're currently having a security issues in permit2 url generation. (_discussed in private chat_)

**Comment by pavlovcik** [comment]
This bounty has no specification. What is the proposal?

**Comment by pavlovcik** [comment]
Also you can link our private group chat messages here and only if you are in the group chat you can read the contents. This will add detail to future specifications even if context is in private group chat.
