### ISSUE TITLE
Config split

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#262]
Right now we have a shared private key with partners for permit2 feature. Partner should be able to set a private key in a private config repository.

Partner should be able to set 2 configs:
1. Organization wide config file located in the `ubiquibot-config` repository at `OWNER/ubiquibot-config/.github/ubiquibot-config.yml` path.
2. Repository wide config file located at a target repository at `OWNER/REPOSITORY/.github/ubiquibot-config.yml` path.

Repository wide config takes precedence over organization wide one. Notice that a repository wide config may not exist.

Sample reference code of how to read file content from a private repository: https://gist.github.com/rndquu/fb13523b8b9536cb7467d96ce6a6f021

So for a partner project the flow will be the following:
1. Create a private repository `ubiquibot-config`
2. Create a config file `.github/ubiquibot-config.yml` with a private key
3. Add the bot to the config repository with the `contents` repository permission

**What should be done**:
1. Implement config split
2. Read private key for the permit2 feature from the config repository 

Notice that here https://github.com/ubiquity/bounty-bot/blob/development/src/bindings/config.ts#L34 it is better to read both from the config and ENV variable for backwards compatibility. When this task is finished we should update the code and read only from the config.

**Comment by 0xcodercrane** [comment]
It looks good in terms of implementation. I am just concerned about the partner sides. So if they don't want to set up a private key repo, automatic payment would be disabled right?

**Comment by rndquu** [comment]
> It looks good in terms of implementation. I am just concerned about the partner sides. So if they don't want to set up a private key repo, automatic payment would be disabled right?

yes

**Comment by pavlovcik** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

I thought that this detects commit activity on the pull request. 

I suppose it only detects if the pull request was opened? 

Let me know I can make a new bounty.

**Comment by Steveantor** [comment]
> 

is the bot running on latest patch?

**Comment by Steveantor** [comment]
> > Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`
> 
> I thought that this detects commit activity on the pull request.
> 
> I suppose it only detects if the pull request was opened?
> 
> Let me know, I can make a new bounty.


is the bot running on latest patch?

**Comment by pavlovcik** [comment]
> > > Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`
> 
> > 
> 
> > I thought that this detects commit activity on the pull request.
> 
> > 
> 
> > I suppose it only detects if the pull request was opened?
> 
> > 
> 
> > Let me know, I can make a new bounty.
> 
> 
> 
> 
> 
> is the bot running on latest patch?
> 
> 
> 
> 

@0xcodercrane should know. I thought it was set up with continuous deployment off of `main` though.

**Comment by 0xcodercrane** [comment]
we should create a PR from `development` into `main`. I will check the merged PRs and create a PR soon

**Comment by Steveantor** [comment]
Permit didn't generate link

**Comment by rndquu** [comment]
> Permit didn't generate link

Perhaps because there is no priority tag hence the reward is not accurate

@pavlovcik could you set the priority tag here and open=>close issue again so that the permit link could be generated
