### ISSUE TITLE
Update partner integration docs

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#263]
Depends on https://github.com/ubiquity/bounty-bot/issues/262

Current partner integration docs: https://dao.ubq.fi/ubiquibot-setup

What should be done:
- update docs so that partners are aware of the config split feature

So for a partner project a new flow will be the following:
1. Create a private repository `ubiquibot-config` 
2. Create a config file `.github/ubiquibot-config.yml`
3. Add the bot to the secrets repository with the `contents` repository permission

Partners can also create repository wide configs.

If partner uses a permit2 feature then he should store private key in a private config repository.

**Comment by pavlovcik** [comment]
Perhaps you should have assigned yourself to claim credit?

**Comment by rndquu** [comment]
> Perhaps you should have assigned yourself to claim credit?

I'm on a payroll so I don't feel this is the right thing to claim bounties.
