### ISSUE TITLE
Comment callback handler

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#269]
Be sure to clean up any deprecated code, such as all of the function calls to manually invoke commenting after all of the other operations.

              > Can you make sure that if there is an error of some sort that it lets us know in a comment?

> From an architecture perspective, a little bit like how I proposed the dynamic help menu architecture, perhaps we can make sort of a standard callback function after a command handler is invoked to always leave a comment/response. In this way, the bounty-bot developer would intentionally have to instruct the bot to not leave a comment/response after a bot command is invoked.

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/issues/192#issuecomment-1502298930_

**Comment by devpanther** [comment]
I don't get this.. are you saying it should display error messages as comments and also some instructions should not give a comment?

> Be sure to clean up any deprecated code, such as all of the function calls to manually invoke commenting after all of the other operations.

This quote above is kinda unclear too

**Comment by pavlovcik** [comment]
The linked comment contains sufficient context on the problem I would say.

**Comment by devpanther** [comment]
> The linked comment contains sufficient context on the problem I would say. 

Okay, I see the it spawned from permit not been generated and nothing was logged to be the problem.

Now a callback should be passed just like we passed the help menu text
