### ISSUE TITLE
Unassigning Bounties

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#41]
### Discussed in https://github.com/ubiquity/bounty-bot/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **pavlovcik** September 10, 2022</sup>

- If the Bounty Hunter took double the allotted time, then they are disqualified for the bounty and the bounty should be released back into the devpool (assigned to @ubiquity-bounties)
- The bot should also leave a comment notifying the Bounty Hunter that they have been disqualified.

### How to resolve

I guess its enough to check out the allocated time once a day. It will basically calculate the passed duration starting from first commit timestamp to current timestamp. 

The first stuff we have to research is to find events which would be triggered regularly, in worst case, we can create new mode which runs every given time period.

**Comment by pavlovcik** [comment]
Can you brief me on how this is implemented?

**Comment by 0xcodercrane** [comment]
I guess we had a bunch of discussions in dm. 
This is my wallet address: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by 0xcodercrane** [comment]
> This should be implemented as a "wild-card post-event handler" instead of as a CRON job

Exactly, it has been implemented as a wildcard post-even handler after deep discussion in https://github.com/ubiquity/bounty-bot/pull/75. I didn't want to open this PR again. but if its out of development rule, I apologize for it.

**Comment by pavlovcik** [comment]
> > oh shit. seems unexpectedly buggy here.
> 
> My hypothesis is that a few bot Actions start and run for 10-20 seconds, and by the time the first one is finished (and it posts the message
> 
> > Releasing the bounty back to dev pool because the allocated duration already ended!
> 
> Its too late for the other ones to notice so they post the same message.
> 
> I think just before posting the comment, we should check if it was already posted in the current conversation.

_from https://github.com/ubiquity/bounty-bot/issues/95#issuecomment-1427231224_

**Comment by 0xcodercrane** [comment]
Let me add a check to handle it

**Comment by 0xcodercrane** [comment]
https://github.com/ubiquity/bounty-bot/commit/47dfaa4cd9bb0b409733bc22237ab74fa8aabec7 -- this should fix the  unassign/reassign issue.
