### ISSUE TITLE
Registering wallet addresses and associating it to each GitHub username

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#42]
### How to resolve
This feature should be working as soon as the linked pull request gets merged. 

 **NOTE**. We're gonna use [supabase](https://supabase.com/docs) to store hunters data. so we should implement database adapter first. 

### Essentials
Please see specification link above for more context.
- On user comment event, invoke a function that will parse the user comment.
- If the user comment starts with the string `/wallet` then we should parse the first address that follows. 
  - This should accomodate both Etherscan links and plaintext addresses.
- Throw errors and comment them from the bot for:
  - Failing to parse an address
  - Failing to update the database
  - Address matches the example (`ubq.eth` or `0xefC0e701A824943b469a694aC564Aa1efF7Ab7dd`)

**Comment by pavlovcik** [comment]
> compare the assignee of issue to the assignee of the linked pull request. If there's difference in hunter naming, it will request bounty masters to confirm.

I disagree. The assignee is the sole responsible party. If somebody else did the PR then the assignee is responsible to pay out the person who helped them. We are only responsible to pay the assignee out if they complete the bounty in time/correctly.

**Comment by 0xcodercrane** [comment]
As a bounty master, if we're only responsible to pay the assignee of the issue, it would be simpler but cleaner. Thanks for your confirmation.

Right. we shouldn't handle the payout if the issue doesn't have a price label. Ok what I was thinking originally was just an automatic way. but yeah we can rediscuss that way later in the discussion section.

**Comment by rndquu** [comment]
If the bot is "stateless" in terms that it is controlled only by commands (like in telegram) then we can not tie ourselves to the merged PRs. We also should not tie ourselves to wallet address with a link to etherscan, I think plain wallet address would be enough.

So the bot just waits for "/wallet 0x01" (in any issue) and saves address to the DB.

**Spec could be the following:**

The bot should be able to register (save in the DB) bounty hunter's wallet address. Bounty hunter can register different wallet addresses so we should track wallet address updates for accounting purposes.

You should implement the bot with the following features:
- when user posts a command "/wallet 0xdafea492d9c6733ae3d56b7ed1adb60692c98bc6" the bot should save wallet address to the supabase DB and associate github username with wallet address
- if there is a validation error of ethereum address then bot should post a message:
```
@author invalid wallet address
```
- on successfull save the bot should respond with:
```
@author wallet address saved
```

**Comment by pavlovcik** [comment]
> can not tie ourselves to the merged PRs

I assume that there is a GitHub Event for this, which means that we can have a handler directly associated with merge PR events. Technically the handler would be "stateless" but we know that the only time it is invoked is when a PR is merged. Within the "context" object passed into the handler, we can see all the information on the PR. 

I like the idea of users posting the Etherscan link for two reasons: 1. I think its considered common practice to share Etherscan links when sharing addresses. 2. It will allow us (and them) to quickly look at their wallet to see if there is any transaction history, which is an indicator of a correct (or incorrect) wallet address.

With that said, we should parse and save only the address in the database; but for quick inspection purposes in the comment, the etherscan link is more convenient.

**Comment by rndquu** [comment]
> I assume that there is a GitHub Event for this

Sure. I meant that it doesn't matter when exactly user registers his wallet address. He can register his wallet address when PR is merged on when issue is assigned to a bounty hunter.

I think this is a normal flow when user assigns a bounty and right after the assignment registers his wallet address, like:
```
/assign
/wallet https://etherscan.com/address/0x01
```

So I mean that registering address when PR merged is not a requirement.

**Comment by pavlovcik** [comment]
Your explanation isn't clear to me. From an architecture perspective, if you're suggesting to run a handler for `/wallet` command and you want the payout to occur even if the PR is merged, this means that the `/wallet` handler should check the `context` object and understand if

1. the PR is merged
2. the payout has not already occurred

If both conditions are true, then the handler can request a payout. 

---

In case I misunderstood your message I also want to add a clarification: I think there's two classes of bounty hunters for the sake of my explanation:

1. new bounty hunters that never solved any bounties yet
4. experienced bounty hunters who have

I expect that 1. will not know/understand the commands. Realistically I think they will learn in time for the second bounty that they take. Also you only should have to assign your `/wallet` one time. This means that the likelihood of a bounty hunter posting both `/assign` and `/wallet` commands in the same comment is very low.

**Comment by rndquu** [comment]
We are not talking about payouts at all. This task is solely about saving wallet address into the DB.

>  you want the payout to occur even if the PR is merged, this means that the /wallet handler should check the context object and understand if

The `/wallet` handler shouldn't check whether PR was merged or not (along with whether payout has already occurred), it just doesn't need it because its only task is to associate github username with wallet address.

Example 1:
1. Bounty hunter clarifies details in an issue
2. Bounty hunter comments `/wallet 0x01` even before the `/assign` command and registers his wallet address

Example 2:
1. Bounty hunter clarifies details in an issue
2. Bounty hunter assigns the issue via `/assign`
3. Bounty hunter updates wallet address via `/wallet 0x01`
4. PR is merged
5. Bounty hunter again updates wallet address via `/wallet 0x02`
6. Payout is made
7. Bounty hunter again updates wallet address via `/wallet 0x03`

I mean that bounty hunter should be able to register his wallet address anytime (even if PR is't merged yet or payout has already occurred). Assigning a wallet should not be event dependent.

**Comment by pavlovcik** [comment]
Technically every handler is event dependent. The event that this handler is invoked by in this case would be on comment.

**Comment by rndquu** [comment]
> Technically every handler is event dependent. The event that this handler is invoked by in this case would be on comment.

Yes, by "event dependent" I meant adding a handler for any new comment (not a merged PR)

**Comment by 0xcodercrane** [comment]
@rndquu  seems right we're gonna register hunters wallet on this issue. 

I agree with `I mean that bounty hunter should be able to register his wallet address anytime`. But we might need a case that the hunter forgets posting a comment `/wallet 0x01` (If I say my perspective, I don't want to post the wallet address until it gets completed)

So I guess if we add a reminder once PR is merged that would be better.

**Comment by pavlovcik** [comment]
> (If I say my perspective, I don't want to post the wallet address until it gets completed)

Why? Its effectively the same if you do it in the beginning or the end of the bounty.

**Comment by 0xcodercrane** [comment]
because there could be a case my PR wouldn't get merged and don't receive payment. In this case, I don't want my wallet address to be tracked by others.

**Comment by pavlovcik** [comment]
You could just make a new wallet address for the bounties...

**Comment by 0xcodercrane** [comment]
If I don't want to create a new wallet because Ethereum gas cost is expensive, you can still push forward me???

**Comment by Steveantor** [comment]
It should be manually updated by the users, using github authentication,
We have to provide UI for that.

The bot shouldn't auto register addresses, unless the user says so.
The `username => address` mapping is also flawed, cause the usernames
could change (we shouldn't force someone to stick with the same username)
user id could be used instead.

**Comment by pavlovcik** [comment]
> It should be manually updated by the users, using github authentication,
> We have to provide UI for that.

I have a loose spec for this https://github.com/ubiquity/ubiquity-dollar/discussions/330

> The bot shouldn't auto register addresses, unless the user says so.

The current plan is that the user should post a comment like this in order to update their information. 
> /wallet 0x29a2416f757b9b46e60309090cd7b6d32c856e43

> cause the usernames
could change (we shouldn't force someone to stick with the same username)
user id could be used instead.

@0xcodercrane and I discussed the database architecture quite a bit and it makes things a LOT easier if we use GitHub user id as the primary key to associate across all of our tables. I'm not totally against your proposal but it does seem like an edge case and will require quite a bit more work to accomodate it from the database perspective.

**Comment by rndquu** [comment]
> maybe we can support both Etherscan and plain wallet address and see how people use it?

I would start simply with a plain wallet address. Adding Etherscan URL is quite a small task which can be added later when plain wallet registration is implemented.

**Comment by pavlovcik** [comment]
> > maybe we can support both Etherscan and plain wallet address and see how people use it?
> 
> I would start simply with a plain wallet address. Adding Etherscan URL is quite a small task which can be added later when plain wallet registration is implemented.

Both should work with the same regex: `/^0x[a-fA-F0-9]{40}$/igm`

**Comment by 0xcodercrane** [comment]
> We might also need an ENS regex.
we can validate ens name using api imo. I don't remember its endpoint exactly but we can definitely do that

**Comment by 0xcodercrane** [comment]
kicking off this issue

**Comment by pavlovcik** [comment]
> kicking off this issue

You heard the bot 

> @0xcodercrane The time limit for this bounty is on 2/22/2023

👹

**Comment by 0xcodercrane** [comment]
`/assign`

**Comment by 0xcodercrane** [comment]
`/assign`

**Comment by 0xcodercrane** [comment]
`/assign`

**Comment by pavlovcik** [comment]
> `/assign`

Doesn't look like it works?
