### ISSUE TITLE
Remind the assignee to push commits at least 1 time within a given period

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#43]
### How to resolve
We should be able to configure the period via .env and config.json. Bounty bot should check the latest commit and remind if no new commits within a given period by posting a message. This check needs to happen every day.

**Comment by pavlovcik** [comment]
>  via .env and config.json

I assume we will roll this all into one `.yml` file for the config instead.

**Comment by 0xcodercrane** [comment]
.yml is the same thing as .env. In GitHub action, env properties are setup in the action yml file.
