### ISSUE TITLE
Announcing new bounties every week in the DevPool

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#44]
### Discussed in https://github.com/ubiquity/bounty-bot/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **pavlovcik** September 10, 2022</sup>

### Communication
- [ ] Announcing new bounties every week in the DevPool
  - If there are bounties that were created and haven't been solved in at least 7 days, then post a message in the Telegram chat every Monday announcing the latest unsolved bounties, along with their prices and links.
  
### How to solve

- [ ] Database schema needs to designed first for managing bounties and pull requests to analyze the bounties. 
- [ ] Need to develop telegram bot adapter to post weekly updates, Afaik, [telegraf](https://www.npmjs.com/package/telegraf) is a powerful npm module we can use. but you can use whatever you prefer.
- [ ] Weekly update needs to be posted exactly once a week.

**Comment by pavlovcik** [comment]
Duplicate
