### ISSUE TITLE
Weekly reviews every week in the DevPool

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#45]
### Discussed in https://github.com/ubiquity/bounty-bot/discussions/69

example:
> We closed seven pull requests last week! 🚀
This week, we added more tests for the ERC20Ubiquity contract, fixed a bug that was causing incorrect balances to be displayed in the footer, added spell checking for dapp and contract scripts, added a custom 404 page, implemented the ERC-2535 Diamond standard, fixed a bunch of Slither issues, adapted the contract to simplify UBQ farming, and fixed a bunch of warnings.

### How to solve
- [ ] database scheme and adapter needs to be completed prior to any analytics features
- [ ] Telegram bot adapter should be completed prior to this issue.
- [ ] Total closed issues, merged pull requests, the number of new bounties released, total payouts, etc. These information needs to be collected once a week and create a proper description for weekly updates with collected information

**Comment by pavlovcik** [comment]
I'm not sure how easy it is to roll our GPT model to handle this vs trying to build off of what-the-diff. A bit of research is needed here.

**Comment by pavlovcik** [comment]
Depends on #47 #54 
Made it a week to figure out how to get chatgpt or gpt3 to summarize info from the GitHub in the previous week

**Comment by pavlovcik** [comment]
> I'm not sure how easy it is to roll our GPT model to handle this vs trying to build off of what-the-diff. A bit of research is needed here.

Stumbled upon this https://github.com/ubiquity/ubiquity-dollar/discussions/519
