### ISSUE TITLE
Design database schemas and developer database adapter

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#46]
### Discussed in https://github.com/ubiquity/bounty-bot/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **pavlovcik** September 10, 2022</sup>

We're gonna plan to use [supabase](https://supabase.com/) which is open-source firebase alternative. This is originally a postgres database. 

The tables we have to basically have are
- [ ] user table
- [ ] issue table
- [ ] payment table

The database adapter is sort of a high level interface for CURL operations.

**Comment by 0xcodercrane** [comment]
kicking off this issue right now.

**Comment by pavlovcik** [comment]
Please share your wallet address here @0xcodercrane

**Comment by 0xcodercrane** [comment]
@pavlovcik This is my wallet address: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by pavlovcik** [comment]
> @pavlovcik This is my wallet address: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

https://etherscan.io/tx/0x74dd4fc9c9bc64c83d556a68166967d39feb519b18b54b810131a1c765296156
