### ISSUE TITLE
Telegram Bot Adapter

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquity/bounty-bot#47]
This is sort of a high level interface to interact with telegram to post weekly updates and announce something.

**Comment by Steveantor** [comment]
I worked with a similar adapter a while back.

**Comment by pavlovcik** [comment]
> I worked with a similar adapter a while back.

As long as you can produce a TypeScript function and create a new bot so that we can test it https://github.com/ubiquity/bounty-bot/issues/54 then both bounties are yours and paid out when we can verify that the code works!

**Comment by Steveantor** [comment]
> > I worked with a similar adapter a while back.
> 
> As long as you can produce a TypeScript function and create a new bot so that we can test it #54 then both bounties are yours and paid out when we can verify that the code works!

sure, I could do that @pavlovcik

**Comment by Steveantor** [comment]
PR #64

**Comment by pavlovcik** [comment]
Hi there! Sorry for the inconvenience but please confirm your wallet address on both of the issues and I will send the payment asap! Thanks for the high quality work.

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by pavlovcik** [comment]
> Here's my address:
> 
> `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
> 
> @pavlovcik 
> 
> 

https://etherscan.io/tx/0xd2fe70d52af81df4ebbd578f9a639f15bcad8b14c83926b3d4ae5e055f1f2a04

https://etherscan.io/tx/0xe277af93099046dfc583c0e13587ed46f649181da83cbd2d62818d8fb4ce7e74
