### ISSUE TITLE
Default Label Colors

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#57]
we should make price labels green; profit/time black

by default i guess thats how its currently set up in the ubiquity-dollar repo

**Comment by ManyRios** [comment]
Hi, Can I help with this issue?

**Comment by sergfeldman** [comment]
> Hi, Can I help with this issue?

@0xcodercrane Is it ok for you that @ManyRios takes this bounty?

**Comment by ManyRios** [comment]
I think this is already done
