### ISSUE TITLE
Improve Unassigning Bounties

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/bounty-bot#95]
Spec https://github.com/ubiquity/bounty-bot/discussions/67

- Be sure to check for comments/commits. If activity from the assignee occurs on the PR, then "top up" the wait time. 
- To clarify, this means that it doesn't matter if the time label is <1 Day, <1 Month, <1 Year; after 4 days, the bot needs to follow up on an update. After 7 days, the bot should disqualify the hunter.
- add config properties:

```
followUpTime= <4 days>
disqualifyTime= <7 days>
```

**Comment by pavlovcik** [comment]
By the way if you have ideas on how to improve this approach please share with me. I am not 100% confident this is the best approach because sometimes vacations/holidays occur and maybe it could get messy. But more most cases, if the bounty hunter is seriously working on the bounty, they shouldn't miss a check-in after 4 days of inactivity...

**Comment by rndquu** [comment]
This https://github.com/ubiquity/bounty-bot/issues/43 seems to be a duplicate issue. We could close https://github.com/ubiquity/bounty-bot/issues/43

**Comment by 0xcodercrane** [comment]
oh shit. seems unexpectedly buggy here.

**Comment by pavlovcik** [comment]
> oh shit. seems unexpectedly buggy here.

My hypothesis is that a few bot Actions start and run for 10-20 seconds, and by the time the first one is finished (and it posts the message 
> Releasing the bounty back to dev pool because the allocated duration already ended!

Its too late for the other ones to notice so they post the same message.

I think just before posting the comment, we should check if it was already posted.

**Comment by 0xcodercrane** [comment]
https://github.com/ubiquity/bounty-bot/issues/124

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x8a8011e1a79cbc6c3c9b8750129031067a2f789d92e1ea3ae97243da6811ce59
