### ISSUE TITLE
Enforce conventional commits

### ISSUE THREAD

**Issue by rndquu** [ubiquity/bounty-bot#97]
We want the repository commit messages to follow the conventional commits pattern. More info: https://www.conventionalcommits.org/en/v1.0.0/

What should be done:
1. On commit (on a local machine) we should check that commit message follows the conventional commits pattern.
2. Add github action that checks commit messages in PR and fails if they do not follow the conventional commits pattern.

**Comment by pavlovcik** [comment]
@Steveantor whats your wallet address

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by pavlovcik** [comment]
> Here's my address:
0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE
@pavlovcik

https://etherscan.io/tx/0x71ba1923ed6772987d29b9b8b709d7c5351566ef3a8675c455bb5a63420c011d
